### ISSUE TITLE
Re-import latest public (2016) MARC records

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary-bots#50]
Using ia-bulkmarc-bot

Item marc_loc_2016 has the following MARC files:
- [x] BooksAll.2016.part01.utf8
- [x] BooksAll.2016.part02.utf8
- [x] BooksAll.2016.part03.utf8
- [x] BooksAll.2016.part04.utf8
- [x] BooksAll.2016.part05.utf8
- [x] BooksAll.2016.part06.utf8
- [x] BooksAll.2016.part07.utf8
- [x] BooksAll.2016.part08.utf8
- [x] BooksAll.2016.part09.utf8
- [x] BooksAll.2016.part10.utf8
- [x] BooksAll.2016.part11.utf8
- [x] BooksAll.2016.part12.utf8
- [x] BooksAll.2016.part13.utf8
- [x] BooksAll.2016.part14.utf8
- [x] BooksAll.2016.part15.utf8
- [x] BooksAll.2016.part16.utf8
- [x] BooksAll.2016.part17.utf8
- [x] BooksAll.2016.part18.utf8
- [x] BooksAll.2016.part19.utf8
- [x] BooksAll.2016.part20.utf8
- [x] BooksAll.2016.part21.utf8
- [x] BooksAll.2016.part22.utf8
- [x] BooksAll.2016.part23.utf8
- [x] BooksAll.2016.part24.utf8
- [x] BooksAll.2016.part25.utf8
- [x] BooksAll.2016.part26.utf8
- [x] BooksAll.2016.part27.utf8
- [x] BooksAll.2016.part28.utf8
- [x] BooksAll.2016.part29.utf8
- [x] BooksAll.2016.part30.utf8
- [x] BooksAll.2016.part31.utf8
- [x] BooksAll.2016.part32.utf8
- [x] BooksAll.2016.part33.utf8
- [x] BooksAll.2016.part34.utf8
- [x] BooksAll.2016.part35.utf8
- [x] BooksAll.2016.part36.utf8
- [x] BooksAll.2016.part37.utf8
- [x] BooksAll.2016.part38.utf8
- [x] BooksAll.2016.part39.utf8
- [x] BooksAll.2016.part40.utf8
- [x] BooksAll.2016.part41.utf8
- [x] BooksAll.2016.part42.utf8
- [x] BooksAll.2016.part43.utf8

**Comment by hornc** [comment]
Completed

**Comment by dechapon25** [comment]
https://github.com/internetarchive/openlibrary-bots/issues/50#issuecomment-752830132
