### ISSUE TITLE
Issue with Cleanup bot adding wrong image

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary-bots#84]
I noticed that cleanup bot added an image here that seems like an error.

Not sure if this could be a systemic issue so thought I'd report it here.

https://openlibrary.org/works/OL6802362W/APL_writing_and_style_guide?_compare=Compare&a=3&b=2&m=diff

**Comment by hornc** [comment]
Thanks @RayBB , Clean up bot was copying the edition cover to the work, unfortunately the edition cover was wrong, set by 
(the now not running) Open Library Bot:
https://openlibrary.org/books/OL4726794M/APL_writing_and_style_guide?_compare=Compare&b=3&a=2&m=diff
I have seen many instances of Open Library Bot's incorrect author and book images, some of them even more innapropriate. I'm not sure where olbot got its images from.   I'll fix manually

**Comment by RayBB** [comment]
That's for the info!
